### ISSUE TITLE
google image search

### ISSUE THREAD

**Issue by 0day1day** [jroimartin/tgbot#4]
!g texttosearch

**Comment by jroimartin** [comment]
Implemented in 166d165aaeb22b205b117fe1a0ee0f59c3d81abd using bing.

**Comment by 0day1day** [comment]
awesome!

2015-03-22 16:53 GMT+01:00 Roi Martin notifications@github.com:

> Implemented in 166d165
> https://github.com/jroimartin/tgbot/commit/166d165aaeb22b205b117fe1a0ee0f59c3d81abd
> using bing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jroimartin/tgbot/issues/4#issuecomment-84640404.

## 

*Manu Quintans *
Independent Malware Researcher & IT Security Specialist

mquintans@zeroday.es - http://www.zeroday.es http://zeroday.es/
